### ISSUE TITLE
Issue running the example provided 

### ISSUE THREAD

**Issue by kimonk** [robinkjoy/systemrdl-compiler#1]
When I try to run the compiler using the provided example, I get the following error:

INFO:Start preprocessing..
INFO:Preprocessing done.
INFO:Start parsing..
INFO:Parsing done.
Traceback (most recent call last):
  File "rdl_compiler.py", line 81, in <module>
    main()
  File "rdl_compiler.py", line 68, in main
    am.populate_addresses(0, 'regalign')
  File "/homes/Athens-BR/kkarras/Projects/systemrdl-compiler/Component.py", line 238, in populate_addresses
    curr_addr = compl.populate_addresses(curr_addr, iaddr_mode, ialign)
  File "/homes/Athens-BR/kkarras/Projects/systemrdl-compiler/Component.py", line 208, in populate_addresses
    if self.at_addr:
AttributeError: 'Signal' object has no attribute 'at_addr'

This happens independently of the output language specified.

**Comment by robinkjoy** [comment]
I pushed some changes from my machine. It's running without errors now.
But it's a work in progress. There is plenty of things to implement/fix. Thanks for your interest. :smiley:

**Comment by kimonk** [comment]
Thanks, it does indeed work. I work at company that's looking for a tool like that to use, so we would be interested in using it and maybe actively contributing to it.

**Comment by robinkjoy** [comment]
You can check out this project too:
https://github.com/Juniper/open-register-design-tool/

**Comment by kimonk** [comment]
I have but I don't like the it produces and the documentation it creates is
not what I'd like to have.
